# For dev environement

version: "3.8"

# networks: use the default network

services:
  # mariadb:
  #   image: mariadb:lts-jammy # TODO var env MYSQL_ROOT_PASSWORD _DATABASE _USER _PASSWORD
  #   container_name: devcurriculum-mariadb-container
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   volumes:
  #     - ../database/data:/database
  #     - ../database/schema:/database/docker-entrypoint-initdb.d/
  #   workdir: /database
  #   build:
  #     context: ../database

  # python:
  #   image: python:slim-bullseye
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ../python:/python
  #   workdir: /python
  #   build:
  #     context: ../python

  # php:
  #   image: php:8.2.9-fpm-alpine3.18
  #   ports:
  #     - "800:80"
  #   volumes:
  #     - ../backend:/var/www/html
  #   workdir: /var/www/html
  #   build:
  #     context: ../backend
  #   depends_on:
  #     - mariadb

  # java: # TODO key/token env var
  #   image: amazoncorretto:17.alpine-amd64 # for dev only, at prod: compile/alpine/JRE
  #   ports:
  #     - "3700:3700"
  #   volumes:
  #     - ../api:/api
  #   workdir: /api
  #   build:
  #     context: ../api
  #   depends_on:
  #     - mariadb

  nginx:
    image: devcurriculum_nginx:1.1
    container_name: devcurriculum_nginx_ctn
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.nginxweb
    ports:
      - "80:80"
    volumes:
      - /usr/share/nginx/html
      - type: volume
        source: compiled_node
        target: /usr/share/nginx/html
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    # depends_on:
    #   - php
    #   - java
    #   - python

  node: 
    image: devcurriculum_node:1.1
    container_name: devcurriculum_node_ctn
    ports:
      - "3000:3000"
    volumes:
      - ../frontend/node:/home/node/app
      - /home/node/app/node_modules
      - type: volume
        source: compiled_node
        target: /home/node/app/node/public
    build:
      context: ../
      dockerfile: docker/Dockerfile.node
    depends_on:
      # - php
      # - java
      # - python
      - nginx

volumes:
  compiled_node: