FROM node:lts-bullseye

# Source
WORKDIR /home/node/app

# Requirements/config
COPY ./frontend/node/package*.json ./
RUN npm install -g npm@latest
RUN npm install
RUN chown -R node:node /home/node/app

# run as non-root with default image user predefined
USER node

# Init
RUN echo "### Node init ###"
CMD ["npm", "run", "start"]