FROM nginx:stable-bullseye

# Source
WORKDIR /usr/share/nginx/html

# Requirements/config
COPY ./docker/config/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/config/nginx/ssl/localhost.crt /etc/nginx/ssl/localhost.crt
COPY ./docker/config/nginx/ssl/localhost.key /etc/nginx/ssl/localhost.key

# nginx already run as non-root by default
USER nginx

# Init
RUN echo "### Nginx init ###"
# Use default init