# For dev environement
# TODO create another compose for prod:
# change all the volumes behavior, no source code bind
# Keep only data of DB, logs, cache, assets in persistence
# No port redirection except front nginx
# TODO wait shell script https://github.com/vishnubob/wait-for-it

version: "3.8"

# networks: use the default network

services:
  mariadb:
    image: mariadb:lts-jammy # TODO var env MYSQL_ROOT_PASSWORD _DATABASE _USER _PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - ../database/data:/database
      - ../database/schema:/database/docker-entrypoint-initdb.d/
    workdir: /database
    build:
      context: ../database

  python_analytics:
    image: python:slim-bullseye
    ports:
      - "8000:8000"
    volumes:
      - ../python:/python
    workdir: /python
    build:
      context: ../python

  php_backend:
    image: php:8.2.9-fpm-alpine3.18
    ports:
      - "800:80"
    volumes:
      - ../backend:/var/www/html
    workdir: /var/www/html
    build:
      context: ../backend
    depends_on:
      - mariadb

  java_api: # TODO key/token env var
    image: amazoncorretto:17.alpine-amd64 # for dev only, at prod: compile/alpine/JRE
    ports:
      - "3700:3700"
    volumes:
      - ../api:/api
    workdir: /api
    build:
      context: ../api
    depends_on:
      - mariadb

  web_frontend:
    image: nginx:stable-bullseye
    ports:
      - "80:80"
    volumes:
      - ../frontend/static:/usr/share/nginx/html
    workdir: /usr/share/nginx/html
    build:
      context: ../frontend/static
    depends_on:
      - php_backend
      - java_api
      - python_analytics

  node_frontend: 
    image: node:lts-bullseye
    ports:
      - "8080:80"
    volumes:
      - ../frontend/typescript:/node
    workdir: /node
    build:
      context: ../frontend/typescript
    depends_on:
      - php_backend
      - java_api
      - python_analytics
      - web_frontend
